# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('fuel_type', models.CharField(blank=True, default='', max_length=64)),
                ('year', models.CharField(blank=True, default='', max_length=32)),
                ('km', models.CharField(blank=True, default='', max_length=32)),
                ('provider', models.CharField(max_length=64)),
                ('identifier', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=200)),
                ('photo_url', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=4096)),
                ('allow_finance', models.NullBooleanField()),
                ('viewed', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.Result')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('provider', 'identifier')]),
        ),
    ]
